### ISSUE TITLE
Table issues

### ISSUE THREAD

**Issue by rcswex** [edward-martyr/Gentium-Xdi8#1]
建议添加图片格式的码位表，并在图片上用文字说明各种功能（汉写输入大写字母、合字等）的调用方法。

**Comment by rcswex** [comment]
码位表应同时放入Release中，方便使用。

**Comment by yuanhao-chen-nyoeghau** [comment]
碼表其實已經在 https://github.com/edward-martyr/Gentium-Xdi8/blob/master/%E7%A2%BC%E4%BD%8D-2.007.png 。功能說明在release中應該也寫得比較完全了。之後會補充在readme裏面。
