### ISSUE TITLE
Double-byte problem

### ISSUE THREAD

**Issue by rcswex** [edward-martyr/Gentium-Xdi8#3]
因为大写字母是安排在CJK双字节码位上的，Windows 下会出现不必要的多于空位。建议在单字节的扩展拉丁也放一下大写字母。

**Comment by yuanhao-chen-nyoeghau** [comment]
Check if that is fixed by the new feature in [2.011](https://github.com/edward-martyr/Gentium-Xdi8/releases/tag/2.011).
